config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users,
             controller: {registrations: 'registrations'}
  root 'posts#index'

  namespace :admin do
    resources :manage_user
    get '/pdf', to: 'manage_users#pdf'
    root to: 'manage_users#index'
  end
  resources :users, only: %i[show destroy]
  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end

  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts, only: %i[index show create destroy] do
    resources :photos, only: [:create]
    resources :likes, only: [:create, :destroy], shallow: true
    resources :comments, only: [:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end

  get 'group', to: 'chatrooms#index'
end

app/models/chatroom.rb
# frozen_string_literal: true

class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :messages
end

app/controllers/chatrooms_controller.rb
# frozen_string_literal: true

class ChatroomsController < ApplicationController
  before_action :set_chatroom, only: %i[show edit update destroy]

  def index
    @chatrooms = Chatroom.all
  end

  def show
    @messages = @chatroom.messages.order(created_at: :desc).limit(100).reverse
    @chatroom_user = current_user.chatroom_users.find_by(chatroom_id: @chatroom.id)
  end

  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit; end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chatroom
    @chatroom = Chatroom.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chatroom_params
    params.require(:chatroom).permit(:name)
  end
end

app/views/chatrooms/_form.html.erb
<%= form_for(chatroom) do |f| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @chatrooms.each do |chatroom| %>
    <tr>
      <td><%= chatroom.name %></td>
      <td><%= link_to 'Show', chatroom %></td>
      <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
      <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to "Join", chatroom_chatroom_users_path(chatroom), method: :post %></td>
      <td><%= link_to "Leave", chatroom_chatroom_users_path(chatroom), method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @chatroom.name %>
</p>

<% unread_messages = false %>
<div data-behavior='messages' data-chatroom-id='<%= @chatroom.id %>'>
  <% @messages.each do |message| %>
    <% if !unread_messages && @chatroom_user.last_read_at < message.created_at %>
      <% unread_messages = true %>
      <div class="strike"><span>Unread Messages</span></div>
    <% end %>

    <%= render message %>
  <% end %>
</div>

<%= form_for [@chatroom, Message.new] do |f| %>
  <%= f.text_area :body, rows: 1, class: "form-control", autofocus: true %>
<% end %>